// <auto-generated />
using System;
using FlightSchedule.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightSchedule.Persistence.EF.Migrations
{
    [DbContext(typeof(FlightScheduleDbContext))]
    partial class FlightScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightSchedule.Domain.Model.CharterSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Airline");

                    b.Property<string>("Airplane");

                    b.Property<string>("FlightNo");

                    b.Property<int>("Seats");

                    b.HasKey("Id");

                    b.ToTable("CharterSchedules");
                });

            modelBuilder.Entity("FlightSchedule.Domain.Model.CharterTimeTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Arrive");

                    b.Property<Guid>("CharterScheduleId");

                    b.Property<DateTime>("Depart");

                    b.Property<string>("Destination");

                    b.Property<string>("Origin");

                    b.HasKey("Id");

                    b.HasIndex("CharterScheduleId");

                    b.ToTable("CharterTimeTables");
                });

            modelBuilder.Entity("FlightSchedule.Domain.Model.CharterTimeTable", b =>
                {
                    b.HasOne("FlightSchedule.Domain.Model.CharterSchedule")
                        .WithMany("TimeTables")
                        .HasForeignKey("CharterScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
